version: '3.8'

services:
  office-control:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./keys:/app/keys:ro
    networks:
      - default

networks:
  default:
    driver: bridge
