services:
  cabine-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: cabine-api:v1
    container_name: cabine_api
    restart: unless-stopped
    ports:
      - 3002:3000
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./keys:/app/keys:ro
    networks:
      - default

networks:
  default:
    driver: bridge
